### ISSUE TITLE
Error : Which Language Would You Like to Use? no working answer found

### ISSUE THREAD

**Issue by rdewolff** [infinitered/gluegun#462]
Hello

Just installed and tried the version, but as soon as I try to run `gluegun` and I have to choose the language, I get errors. 

Tried the following : 

```
gluegun new mm                                                              1 ↵
✔ Which language would you like to use? · TypeScript
/Users/rdewolff/.config/yarn/global/node_modules/gluegun/build/index.js:13
    throw up;
    ^

TypeError: answer.toLowerCase is not a function
    at Object.<anonymous> (/Users/rdewolff/.config/yarn/global/node_modules/gluegun/build/cli/commands/new.js:99:58)
    at step (/Users/rdewolff/.config/yarn/global/node_modules/gluegun/build/cli/commands/new.js:32:23)
    at Object.next (/Users/rdewolff/.config/yarn/global/node_modules/gluegun/build/cli/commands/new.js:13:53)
    at fulfilled (/Users/rdewolff/.config/yarn/global/node_modules/gluegun/build/cli/commands/new.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

```
gluegun new mm                                                              1 ↵

✔ Which language would you like to use? · typescript
/Users/rdewolff/.config/yarn/global/node_modules/gluegun/build/index.js:13
    throw up;
    ^

TypeError: answer.toLowerCase is not a function
    at Object.<anonymous> (/Users/rdewolff/.config/yarn/global/node_modules/gluegun/build/cli/commands/new.js:99:58)
    at step (/Users/rdewolff/.config/yarn/global/node_modules/gluegun/build/cli/commands/new.js:32:23)
    at Object.next (/Users/rdewolff/.config/yarn/global/node_modules/gluegun/build/cli/commands/new.js:13:53)
    at fulfilled (/Users/rdewolff/.config/yarn/global/node_modules/gluegun/build/cli/commands/new.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

```
gluegun new mm                                                              1 ↵

✔ Which language would you like to use? · Typescript
/Users/rdewolff/.config/yarn/global/node_modules/gluegun/build/index.js:13
    throw up;
    ^

TypeError: answer.toLowerCase is not a function
    at Object.<anonymous> (/Users/rdewolff/.config/yarn/global/node_modules/gluegun/build/cli/commands/new.js:99:58)
    at step (/Users/rdewolff/.config/yarn/global/node_modules/gluegun/build/cli/commands/new.js:32:23)
    at Object.next (/Users/rdewolff/.config/yarn/global/node_modules/gluegun/build/cli/commands/new.js:13:53)
    at fulfilled (/Users/rdewolff/.config/yarn/global/node_modules/gluegun/build/cli/commands/new.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

What's going on ?

**Comment by jamonholmgren** [comment]
Probably related to @sw-yx's PR #458? Want to take a crack at fixing this, @rdewolff ?
